data:
  raw: ../../data/raw/01_hdb_resale_transactions.csv
  ppath: ../../data/processed/

setup:
  target: resale_price
  trainsize: 0.8
  transform: True
  norm: True
  session: 123
  logexp: True
  expname: hdb_experiment
  rmoutlier: True
  fold: 10
  date: month
  bin: postal_code
  sample: 0.6            # will sample to half the datasize to make models run faster so jupyter wont crash
  ignore: 
    - block
    - latitude
    - longitude

