hydra:
  output_subdir: null  
  run:
    dir: .

defaults:
  - process: process1
  - model: model1
  - _self_

data:
  raw: ${hydra:runtime.cwd}/../data/raw/sample.csv
  processed: ${hydra:runtime.cwd}/../data/processed/processed.csv
  final: ${hydra:runtime.cwd}/../data/final/final.csv

data_RJ:
  raw: ../data/raw/01_hdb_resale_transactions.csv
  processed: ${hydra:runtime.cwd}/../data/processed/processed.csv
  final: ${hydra:runtime.cwd}/../data/final/final.csv
  
data_Shermaine:
  raw: ../data/raw/02_medical_records.csv
  processed: ${hydra:runtime.cwd}/../data/processed/processed.csv
  final: ${hydra:runtime.cwd}/../data/final/final.csv